version: "3.8"
services:
  web:
    build: 
      context: ./frontend
      args: 
        REACT_APP_API_URL : "https://frontend-backend-ghactions-backend.onrender.com"
      
    depends_on:
      - api
    ports:
      - "3000:3000"
    networks:
      - network-backend
  api:
    build: ./backend
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    networks: 
     - network-backend
  
  mongo:
    image: mongo
    restart: always
    volumes: 
      - mongodb_data:/data/db
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: "rumanmlk123_db_user"
      MONGODB_INITDB_ROOT_PASSWORD: "@f*EiC2.rRA4ZCf"
    # uncomment following lines to access db locally
    # ports:
    #   - 27017:27017
    networks: 
     - network-backend

networks:
  network-backend:

volumes: 
  mongodb_data:
