name: Render-Deploy

on:
  workflow_dispatch:
    inputs:
      tag_frontend:
        type: string
        description: Enter Frontend Image Tag Name
        required: true
        default: latest
      tag_backend:
        type: string
        description: Enter Backend Image Tag Name
        required: true
        default: latest

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      deployments: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


       ########################BACKEND######################################
 
      - name: Render Deploy Backend
        run: curl "https://api.render.com/deploy/${{secrets.BACKEND_SERVICE_ID}}?key=nTefl6AW10o&imgURL=docker.io/${{env.IMAGE_NAME}}-backend:${{ github.event.inputs.tag_backend }}"


      ########################FRONTEND####################################

      - name: Extract Backend URL
        id: url_backend
        run: |
          response=$(curl --request GET \
          --url https://api.render.com/v1/services/${{secrets.BACKEND_SERVICE_ID}} \
          --header 'accept: application/json' \
          --header 'authorization: Bearer ${{secrets.RENDER_TOKEN}}')

          backend_url=$(echo "$response" | jq -r '.serviceDetails.url')

          echo "backend_url=$backend_url" >> $GITHUB_OUTPUT


      - name: REACT_APP_API_URL Env var in Render
        run: |
          curl --request PUT \
          --url https://api.render.com/v1/services/${{ secrets.FRONTEND_SERVICE_ID }}/env-vars/REACT_APP_API_URL \
          --header 'accept: application/json' \
          --header 'authorization: Bearer ${{ secrets.RENDER_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '
            {
              "value": "${{ steps.url_backend.outputs.backend_url }}"
            }
            '

      - name: Render Deploy Frontend
        run:  curl "https://api.render.com/deploy/${{secrets.FRONTEND_SERVICE_ID}}?key=GUdiiHbPF2k&imgURL=docker.io/${{env.IMAGE_NAME}}-frontend:${{ github.event.inputs.tag_frontend }}"